default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :test do
    run_tests(
      project: "DateCard.xcodeproj",
      scheme: "DateCardTests",
      device: "iPhone 17 Pro",
      clean: true
    )
  end

  desc "Build for TestFlight"
  lane :beta do
    increment_build_number
    build_app(
      project: "DateCard.xcodeproj",
      scheme: "DateCard",
      export_method: "app-store"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Deploy to App Store"
  lane :release do
    increment_build_number
    build_app(
      project: "DateCard.xcodeproj",
      scheme: "DateCard",
      export_method: "app-store"
    )
    upload_to_app_store(
      submit_for_review: false,
      force: true
    )
  end
end
